/**
 * UGL Artefact catalogue — public surface.
 *
 * The 180-row data array lives in the auto-generated sibling file
 * ./ugl-artefacts-data.ts (regenerated by scripts/generate_ugl_artefacts.py
 * from the UGL Atlas xlsx). This file re-exports the data and adds the
 * hand-written query helpers consumers actually call.
 *
 * The data file also runs a runtime sanity assertion at module-load time
 * that locks down expected SOR -> artefact counts; that fires during
 * `next build` if the generator ever regresses.
 */

export { UGL_ARTEFACTS, type UglArtefact } from "./ugl-artefacts-data";
import { UGL_ARTEFACTS, type UglArtefact } from "./ugl-artefacts-data";

/**
 * Return the artefacts UGL requires for a given SOR code, in board order
 * (Atlas 6.0 row order — categories grouped, artefact numbers ascending).
 */
export function artefactsForSor(sorCode: string): UglArtefact[] {
  return UGL_ARTEFACTS.filter((a) => a.sorCodes.includes(sorCode));
}

/**
 * Distinct UGL Categories that apply to a SOR code, in first-seen order.
 * For CW-01-01-24 this returns ["Open Cut Excavation", "Directional Drilling/Grundo Mat"]
 * — the method picker chooses one to render.
 */
export function categoriesForSor(sorCode: string): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const a of artefactsForSor(sorCode)) {
    if (!seen.has(a.category)) {
      seen.add(a.category);
      out.push(a.category);
    }
  }
  return out;
}

/**
 * Friendly card-header label. If the SOR maps to exactly one UGL Category
 * we use that (e.g. CW-02-03-02 → "ACM Pit Removal"). If multiple categories
 * apply (CW-01-01-24 spans Open Cut + Directional Drilling) we fall back to
 * the UGL Item label (e.g. "Conduit Install").
 */
export function workNatureForSor(sorCode: string): string {
  const cats = categoriesForSor(sorCode);
  if (cats.length === 1) return cats[0];
  const arts = artefactsForSor(sorCode);
  return arts[0]?.item ?? sorCode;
}

/**
 * Narrow a SOR's artefact list by the chosen Work Method label (the value of
 * SOR_COLUMNS.WORK_METHOD on monday — e.g. "Trenching", "Drilling (HDD)",
 * "Drilling + Trenching", "To Be Decided").
 *
 * Only matters for the duct SORs (CW-01-01-*) which have artefacts in BOTH
 * "Open Cut Excavation" and "Directional Drilling/Grundo Mat" — the crew's
 * pick decides which subset is required. For every other SOR the artefacts
 * have a single category so we return them all unchanged.
 *
 * When a SOR is method-ambiguous and the method hasn't been picked yet
 * ("To Be Decided" or null), we return [] — strict completion treats nothing
 * as required until the picker has fired, and the asset page renders the
 * "Method not yet selected" placeholder instead of artefact tiles.
 */
export function filterArtefactsByMethod(
  artefacts: UglArtefact[],
  workMethod: string | null | undefined
): UglArtefact[] {
  const cats = new Set(artefacts.map((a) => a.category));
  const isMethodAmbiguous =
    cats.has("Open Cut Excavation") &&
    cats.has("Directional Drilling/Grundo Mat");
  if (!isMethodAmbiguous) return artefacts;

  switch (workMethod) {
    case "Trenching":
      return artefacts.filter((a) => a.category === "Open Cut Excavation");
    case "Drilling (HDD)":
      return artefacts.filter(
        (a) => a.category === "Directional Drilling/Grundo Mat"
      );
    case "Drilling + Trenching":
      return artefacts.filter(
        (a) =>
          a.category === "Open Cut Excavation" ||
          a.category === "Directional Drilling/Grundo Mat"
      );
    default:
      // Method not yet picked — strict completion treats nothing as required.
      return [];
  }
}
